<a href="https://colab.research.google.com/github/DhanaTejaDumpa/numpy_practise/blob/main/000_21Jan25_numpy_task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 21/01/2025

# 1) Explain Data Analysis in your own words using a markdown cell/code cell.

## Data Analysis :
 Data Analysis is the process of systematically applying statistical and/or logical techniques to describe and illustrate, condense and recap, and evaluate data.

  (or)

Data analytics converts raw data into actionable insights. It includes a range of tools, technologies, and processes(examining, organizing, and interpreting data) used to find trends, patterns and solve problems by using data. Data analytics can shape business processes, improve decision-making, and foster business growth.

## Key Steps in Data Analysis :               
1) <u>Collecting Data</u>: Gathering raw information from various sources (e.g., surveys, databases, or experiments).

2) <u>Cleaning Data</u>: Removing errors, duplicates, or incomplete information to ensure accuracy.

3) <u>Organizing Data</u>: Arranging the data in a structured way (e.g., in tables or spreadsheets).

4) <u>Analyzing Data</u>: Using tools and techniques (like graphs, statistics, or software) to identify patterns or trends.

5) <u>Drawing Conclusions</u>: Making sense of the findings to answer questions or solve problems.

6) <u>Sharing Results</u>: Presenting the insights clearly using charts, reports, or presentations


### Example:

Imagine you run a bakery and want to know which pastries are most popular. By analyzing sales data:

* You can see which items sell the most.

* Spot trends, like higher sales on weekends.

* Adjust your production to meet customer demand and reduce waste.

# 2) Explain the difference between a function, a module, and a package in Python. Provide examples for each concept.


## <u>Functions</u> :

A function is a block of reusable code that performs a specific task. In the context of NumPy, functions are operations or calculations that can be applied to arrays or matrices. NumPy provides a wide range of functions, including mathematical, statistical, and linear algebra functions.



In [ ]:
# Example :

import numpy as np

arr = np.arange(5)                       # creating an 1D array
mean_arr = np.mean(arr)                  # calculating mean of array using numpy function ,np.mean()
mean_arr

2.0

## <u>Module</u> :             

A module is a file containing Python code that defines functions, classes, and variables, and it can include runnable code. A module can be imported into other Python programs to provide its functionality.

NumPy itself is a module that provides a wide variety of functions for numerical computing. When you import NumPy, you can use its functions and classes to perform operations on arrays.

In [ ]:
# Example :

import numpy as np


arr = np.array([1, 2, 3, 4, 5])           # Creating a NumPy array using the NumPy module
arr


array([1, 2, 3, 4, 5])

## <u>Package</u> :            

A package is a collection of Python modules organized in directories, with an optional \_\_init__.py file to indicate that the directory is a package. Packages allow for the grouping of related modules, making code more modular and organized.

In the case of NumPy, it's a package because it contains multiple modules and submodules that are organized under the numpy directory

**Note** :
* A python module may contain several classes,functions,variables etc.whereas python package can contain several modules.In simpler terms a package is folder that contains various modules as files.


* <b><i>Packages</i></b> are folder like structure which contains multiple <b><i>modules</b></i>.

# Package structure :               

* First we have to create a package folder.
* inside folder create multiple files(suppose 3)
  * \_\_init__.py (initialisation file)
  * module1.py
  * module2.py

* If we want to create a package then that folder must contain an initialisation file(\_\_init__.py).This file makes the intialisation of package.
* If we donot create an intialisation file under package folder,then it won't be considered as package.

**Note :**
* Python packages require a specific directory structure, including an \_\_init__.py file, which acts as a marker for the directory to be treated as a package.
* In `Colab` or `jupyter` Notebooks, creating and maintaining such a directory structure is not straightforward, as these environments are not designed for full project development workflows.
* While workarounds using <u>%mkdir</u> and <u>%writefile</u> commands can simulate a package, this is not an ideal or practical approach for complex projects.
* Development environments like <mark>VS Code, PyCharm, or any local Python environment</mark> are more suitable for creating and managing Python packages. These IDEs provide tools like file explorers, templates, and testing integrations to streamline package development.








myPackage/

  \_\_init__.py                           # make it a package

  basicOperations.py                      # module1

  advancedOperations.py                   # module2

basicOperations.py                                    

In [ ]:
# create module1

def add(a,b):
  return a+b

def subtract(a,b):
  return a-b

advacedOperations.py

In [ ]:
# create module2

def product(a,b):
  return a*b

def power(a,n):
  return a**n


**we can use my_package in our files by importing it**

In [ ]:
# from myPackage.basicOperations import add,subtract
# from myPackage.advancedOperations import product,power


print(f'sum = {add(2,3)}')
print(f'difference = {subtract(2,3)}')
print(f'product = {product(2,3)}')
print(f'power = {power(2,3)}')

sum = 5
difference = -1
product = 6
power = 8


# <u>Difference between function,module and package</u> :

Function|Module|Package
--------|------|-------
A reusable block of code that performs a task.|A single Python file containing reusable code.|A folder containing related modules (and sub-packages).
ex:  def greet(name): return "Hello!"|ex:  import math,import numpy| ex : from myPackage import basicOperations

# 3) Write a Python program that:
# Creates a numpy array using the values 4, 5, 6, 7, 8.

#Prints the created array to display the result.

In [ ]:
lst = [4,5,6,7,8]                       # given values are taken as list
arr = np.array(lst)                     # creating an array using a list
print(arr)                              # prints the array

[4 5 6 7 8]


# 4) Create a numpy array takeing input from the user and print the created array

In [ ]:
import numpy as np

num = int(input('Enter num of inputs you want to enter : '))
lst = []

for i in range(num) :
  lst.append(int(input('Enter your number : ')))

arr = np.array(lst)
arr


Enter num of inputs you want to enter : 3
Enter your number : 1
Enter your number : 2
Enter your number : 3


array([1, 2, 3])

In [ ]:
# alternative method

input_lst = input('Enter your numbers separated by spaces : ')
lst = list(map(float,input_lst.split()))
arr = np.array(lst)
arr

Enter your numbers separated by spaces : 1 2 3 4 5


array([1., 2., 3., 4., 5.])