<a href="https://colab.research.google.com/github/DhanaTejaDumpa/numpy_practise/blob/main/001_23Jan25_numpy_2_task2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 23/01/2025

# 1) a) Generate five NumPy arrays of different dimensions using arange().
# b) Determine the datatype, shape, size, and dimensions of those arrays.


In [ ]:
import numpy as np

In [ ]:
# creating a 1D array :

arr1 = np.arange(5)
arr1

array([0, 1, 2, 3, 4])

In [ ]:
print(f'datatype : {arr1.dtype}, shape : {arr1.shape}, size : {arr1.size}, dimensions : {arr1.ndim}')

datatype : int64, shape : (5,), size : 5, dimensions : 1


In [ ]:
# creating a 2D array :

arr2 = np.arange(6).reshape(2,3)
arr2

array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
print(f'datatype : {arr2.dtype}, shape : {arr2.shape}, size : {arr2.size}, dimensions : {arr2.ndim}')

datatype : int64, shape : (2, 3), size : 6, dimensions : 2


In [ ]:
# creating a 3D array :

arr3 = np.arange(27).reshape(3,3,3)
arr3

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
print(f'datatype : {arr3.dtype}, shape : {arr3.shape}, size : {arr3.size}, dimensions : {arr3.ndim}')

datatype : int64, shape : (3, 3, 3), size : 27, dimensions : 3


In [ ]:
# create a 4D array :

arr4 = np.arange(64).reshape(2,4,2,4)
arr4

array([[[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7]],

        [[ 8,  9, 10, 11],
         [12, 13, 14, 15]],

        [[16, 17, 18, 19],
         [20, 21, 22, 23]],

        [[24, 25, 26, 27],
         [28, 29, 30, 31]]],


       [[[32, 33, 34, 35],
         [36, 37, 38, 39]],

        [[40, 41, 42, 43],
         [44, 45, 46, 47]],

        [[48, 49, 50, 51],
         [52, 53, 54, 55]],

        [[56, 57, 58, 59],
         [60, 61, 62, 63]]]])

In [ ]:
print(f'datatype : {arr4.dtype}, shape : {arr4.shape}, size : {arr4.size}, dimensions : {arr4.ndim}')

datatype : int64, shape : (2, 4, 2, 4), size : 64, dimensions : 4


In [ ]:
# creating a 5D array :

arr5 = np.arange(80).reshape(2,2,2,2,5)
arr5

array([[[[[ 0,  1,  2,  3,  4],
          [ 5,  6,  7,  8,  9]],

         [[10, 11, 12, 13, 14],
          [15, 16, 17, 18, 19]]],


        [[[20, 21, 22, 23, 24],
          [25, 26, 27, 28, 29]],

         [[30, 31, 32, 33, 34],
          [35, 36, 37, 38, 39]]]],



       [[[[40, 41, 42, 43, 44],
          [45, 46, 47, 48, 49]],

         [[50, 51, 52, 53, 54],
          [55, 56, 57, 58, 59]]],


        [[[60, 61, 62, 63, 64],
          [65, 66, 67, 68, 69]],

         [[70, 71, 72, 73, 74],
          [75, 76, 77, 78, 79]]]]])

In [ ]:
print(f'datatype : {arr5.dtype}, shape : {arr5.shape}, size : {arr5.size}, dimensions : {arr5.ndim}')

datatype : int64, shape : (2, 2, 2, 2, 5), size : 80, dimensions : 5


# 2) a) Generate five NumPy arrays of different dimensions using np.array().
# b) Determine the datatype, shape, size, and dimensions of those arrays.


In [ ]:
import numpy as np

In [ ]:
# creating a 1D array :

arr1 = np.array([1,2,3,4,5])
arr1

array([1, 2, 3, 4, 5])

In [ ]:
print(f'datatype : {arr1.dtype}, shape : {arr1.shape}, size : {arr1.size}, dimensions : {arr1.ndim}')

datatype : int64, shape : (5,), size : 5, dimensions : 1


In [ ]:
# creating a 2D array :

lst1 = [[1,2],[3,4]]
arr2 = np.array(lst1)
arr2

array([[1, 2],
       [3, 4]])

In [ ]:
print(f'datatype : {arr2.dtype}, shape : {arr2.shape}, size : {arr2.size}, dimensions : {arr2.ndim}')

datatype : int64, shape : (2, 2), size : 4, dimensions : 2


In [ ]:
# creating a 3D array :

lst1 = [[1,2],[3,4]]
lst2 = [[5,6],[7,8]]
arr3 = np.array((lst1,lst2))
arr3

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [ ]:
print(f'datatype : {arr3.dtype}, shape : {arr3.shape}, size : {arr3.size}, dimensions : {arr3.ndim}')

datatype : int64, shape : (2, 2, 2), size : 8, dimensions : 3


In [ ]:
# creating a 4D array :

lst3d1 = [[[1,2],[3,4]],[[5,6],[7,8]]]
lst3d2 = [[[9,10],[11,12]],[[13,14],[15,16]]]
arr4 = np.array((lst3d1,lst3d2))
arr4

array([[[[ 1,  2],
         [ 3,  4]],

        [[ 5,  6],
         [ 7,  8]]],


       [[[ 9, 10],
         [11, 12]],

        [[13, 14],
         [15, 16]]]])

In [ ]:
print(f'datatype : {arr4.dtype}, shape : {arr4.shape}, size : {arr4.size}, dimensions : {arr4.ndim}')

datatype : int64, shape : (2, 2, 2, 2), size : 16, dimensions : 4


In [ ]:
# creating a 5D array :

lst4d1 = [[[[1, 2], [3, 4]], [[5, 6], [7, 8]]], [[[9, 10], [11, 12]], [[13, 14], [15, 16]]]]
lst4d2 = [[[[31,32], [33,34]], [[35, 36], [37, 38]]], [[[39, 40], [41, 42]], [[43, 44], [45, 46]]]]

arr5 = np.array((lst4d1,lst4d2))
arr5

array([[[[[ 1,  2],
          [ 3,  4]],

         [[ 5,  6],
          [ 7,  8]]],


        [[[ 9, 10],
          [11, 12]],

         [[13, 14],
          [15, 16]]]],



       [[[[31, 32],
          [33, 34]],

         [[35, 36],
          [37, 38]]],


        [[[39, 40],
          [41, 42]],

         [[43, 44],
          [45, 46]]]]])

In [ ]:
print(f'datatype : {arr5.dtype}, shape : {arr5.shape}, size : {arr5.size}, dimensions : {arr5.ndim}')

datatype : int64, shape : (2, 2, 2, 2, 2), size : 32, dimensions : 5
