<a href="https://colab.research.google.com/github/DhanaTejaDumpa/numpy_practise/blob/main/002_24Jan25_arrayOperations_task3.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Date : 24/01/2025

# <center><u>**Array Functions**</u></center>

## 1) a. Generate a numpy array with arange() function. .
## - Access element at the second index of the NumPy array.
## - Slice the first three elements.


In [ ]:
import numpy as np

In [ ]:
# creating a 1D array

arr = np.arange(1,21,2)
arr

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [ ]:
# accessing the element at second index

arr[2]

5

In [ ]:
# slicing first three elements

arr[:3]

array([1, 3, 5])

## 1) b. Create a 2D array .
## - Access the element in the second row and third column of the 2D array.
## - Slice the first two rows and columns of the 2D array.


In [ ]:
# creating a 2D array

arr2 = np.arange(1,11).reshape(2,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [ ]:
# accessing the element in the second row of third column

arr2[1,2]

8

In [ ]:
# slicing first two rows and columns

arr2[0:2,0:2]

array([[1, 2],
       [6, 7]])

## 2) a.Create an array that includes values from 1 to 10 with a step of 2.



In [ ]:
arr = np.arange(1,11,2)
arr

array([1, 3, 5, 7, 9])

## 2) b. Create a 2x3 array using reshape() from a 1D array with values 1 to 6.

In [ ]:
arr2 = np.arange(1,7).reshape(2,3)
arr2

array([[1, 2, 3],
       [4, 5, 6]])

## 3) Create a 3D array print its shape and then use squeeze() to remove the singleton dimension. Display both the input and output arrays along with their shapes.

In [ ]:
# Note :  The singleton dimensions are the dimensions with size 1.

arr3 = np.arange(6).reshape(1,2,3)
print(f'array : {arr3},array shape : {arr3.shape}')

array : [[[0 1 2]
  [3 4 5]]],array shape : (1, 2, 3)


In [ ]:
arr3.squeeze()
print(f'squeezed array : {arr3.squeeze()}, squeezed array shape : {arr3.squeeze().shape}')

squeezed array : [[0 1 2]
 [3 4 5]], squeezed array shape : (2, 3)


## 4) Create a 2D NumPy array and use np.expand_dims() to add singleton dimensions. Show the array and its shape before and after each operation.

In [ ]:
arr2 = np.arange(4).reshape(2,2)
print(f'array : {arr2},array shape : {arr2.shape}')

(array([[0, 1],
        [2, 3]]),
 (2, 2),
 2)

In [ ]:
ex_arr2 = np.expand_dims(arr2,0)
print(f'expanded array : {ex_arr2},expanded array shape : {ex_arr2.shape}')

expanded array : [[[0 1]
  [2 3]]],expanded array shape : (1, 2, 2)
