<a href="https://colab.research.google.com/github/DhanaTejaDumpa/numpy_practise/blob/main/003_28Jan25_broadCasting_randomFunc_task4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 28/01/2025

## 1) Explain the rules of broadcasting ?

## <b><u>Broad Casting:</b></u>

Broadcasting in NumPy allows operations on arrays of different shapes by automatically expanding one or both arrays to a compatible shape, without requiring explicit reshaping. It simplifies arithmetic operations like addition, subtraction, multiplication, and division between arrays of different dimensions.

**Note :** If the arithmetic operations are performed with arrays of exact same shape, then the operations are done element-to-element

<u>**key rules of broadcasting**</u> :

* Broadcasting works solely based on the shape of arrays.

<mark>1) Handling Dimension Mismatch</mark>

* If array dimensions differ, add ones to the left of the smaller array's shape until dimensions match.

<mark>2) Expanding Singleton Dimensions</mark>

* If a dimension has size 1, expand it to match the corresponding size of the other array.(If there any one's in the shape of array increase one's with respective index of element of other array)

<mark>3) Outcome</mark>

**Shapes are equal**: Broadcasting succeeds, and operations can proceed.

**Shapes are incompatible**: Mathematical operations cannot be performed.

#### <u>Example</u>:

Array1: Shape (3, 1)

Array2: Shape (3, 4)

<u>Result</u>: Array1 broadcasts to (3, 4).






## 2) Create a 2D array named array1 of shape(3,4) using random values between 1 and 10 and create another 2D array named array2 of shape(4,) using random values between 1 and 10.

### a) Perform element-wise addition between array1 and array2.print the result.
### b) perform element-wise multiplication between array1 and array2.print the resullt and explain how broadcasting applies in this case.

In [ ]:
import random

In [ ]:
import numpy as np

In [ ]:
# creating a 2D array1 of shape(3,4) using random values between 1 and 10

array1 = np.random.randint(1,10,(3,4))
array1

array([[2, 8, 8, 1],
       [3, 4, 3, 6],
       [9, 2, 1, 8]])

In [ ]:
# creating a 2D array2 of shape(4,) using random values between 1 and 10

array2 = np.random.randint(1,10,(4,))
array2

array([7, 3, 1, 9])

In [ ]:
# a)Perform element-wise addition between array1 and array2.

array1 + array2


array([[ 9, 11,  9, 10],
       [10,  7,  4, 15],
       [16,  5,  2, 17]])

**Expalanation for addition between array1 and array2 :**

1) Dimensions of both arrays are not same.--- add 1 from leftside to shape of array2.so, shape of array2 (4,) becomes (1,4)

2) if '1' is available in shape of array2 , then increase '1' to the respective index of array1. Now , shape of array2 (1,4) becomes (3,4)

3) shape of array2(3,4) is same as shape of array1(3,4).

4) Hence array2 can be broadcasted to array1.so,we can perform mathemetical operations(here addition).

In [ ]:
# perform element-wise multiplication between array1 and array2.

array1 * array2


array([[14, 24,  8,  9],
       [21, 12,  3, 54],
       [63,  6,  1, 72]])

**Expalanation for element-wise multiplication:**

1) Dimensions of both arrays are not same.--- add 1 from leftside to shape of array2.so, shape of array2 (4,) becomes (1,4)

2) if '1' is available in shape of array2 , then increase '1' to the respective index of array1. Now , shape of array2 (1,4) becomes (3,4)

3) shape of array2(3,4) is same as shape of array1(3,4).

4) Hence array2 can be broadcasted to array1.so,we can perform mathematical operations(here multiplication).

## 3) Create a 2D array named array1 of shape(3,4) using random values between 20 and 30 and create another 2D array named array2 of shape(3,5) using random values between 1 and 10.

### a) Try to add array1 and array2 together and explain why we got error here?

In [ ]:
# Creating a 2D array named array1 of shape(3,4) using random values between 20 and 30

array1 = np.random.randint(20,30,(3,4))
array1

array([[22, 25, 21, 28],
       [21, 25, 24, 22],
       [28, 23, 25, 20]])

In [ ]:
# Creating a 2D array named array2 of shape(3,5) using random values between 1 and 10

array2 = np.random.randint(1,10,(3,5))
array2

array([[4, 7, 4, 5, 8],
       [7, 4, 1, 5, 5],
       [6, 8, 7, 7, 3]])

In [ ]:
# adding array1 and array2

array1 + array2

NameError: name 'array1' is not defined

**Expalanation for addition array1 between array2:**

1) Dimensions of both arrays are  not same here .(second dimension of both arrays are not same (4 and 5).)

2) And also neither dimension is 1.

3) Hence, array2 can not be broadcasted to array1 .so,we cannot perform addition operation.


## 4) Explain the differences between rand,randn,randint, and uniform with examples?

## <b><u>rand()</u></b> :

The rand() function in Python,typically from libraries like NumPy or PyTorch, generates random values drawn from a uniform distribution over the range [0, 1). You can specify the shape of the array to determine how many random values are returned and in what structure.

**Note :** Every element will be within the range of [0,1)


      syntax : numpy.random.rand(d0, d1, ..., dn)

* d0,d1, - - -, dn are specific dimensions of returned array(optional)(should be positive values).If you donot mention any dimensions,rand() returns a random float value.


In [ ]:
# generate a single random value

value = np.random.rand()
value

0.14260031444628352

In [ ]:
# generate an array of shape(1,2)

array = np.random.rand(1,2)
array

array([[0.173608  , 0.96660969]])

### <b><u>randn()</u></b> :

The randn() function generates random values drawn from the standard normal distribution (mean = 0, standard deviation = 1). The user specifies the shape of the output, and the function returns random values in that structure.

**Note :** Every element will be within range of normal distribution(0,1)

     syntax : numpy.random.randn(d0, d1, ..., dn)

* d0,d1, - - -, dn are specific dimensions of returned array(optional)(should be positive values).If you donot mention any dimensions,randn() returns a random float value.


In [ ]:
# generate a single random value

value = np.random.randn()
value

0.1088634678336795

In [ ]:
# generate an array of shape(1,2)

array = np.random.randn(1,2)
array

array([[ 0.50780959, -0.86222735]])

## <b><u>randint()</u></b> :            

The randint() function generates random integers from a specified range
[low,high). The user can define the range and the shape of the output.

**Note :** low value is inclusive and high value is exclusive.

    syntax : numpy.random.randint(low, high=None, size=None)

* low : lower bound value(inclusive)
* high(optional) : higher bound value(exclusive)
* size(optional) : specify output shape.Default is None means returns a single value


In [ ]:
# generate a single random integer value

int_value = np.random.randint(1,10)
int_value

8

In [ ]:
# generate an array of shape(3,4)

int_array = np.random.randint(1,10,(3,4))
int_array

array([[4, 3, 4, 9],
       [8, 2, 6, 4],
       [1, 7, 3, 4]])

### <u><b>uniform()</b></u> :              
The uniform() function generates random numbers from a uniform distribution over the range [low,high), where all values are equally likely, with low as the inclusive lower bound, high as the exclusive upper bound, and size specifying the shape of the output array.

    syntax : numpy.random.uniform(low, high, size=None)

* low : lower bound of range.(inclusive)
* high : higher bound of range(exclusive)
* size(optional) : specify output shape.Default value is None means returns a single random number.

In [ ]:
# generate a single random value

value = np.random.uniform(2,5)
value


4.783140721413223

In [ ]:
# generate an array of shape (3,4) in range(1,2)

array = np.random.uniform(1,2,(3,4))
array

array([[1.38659638, 1.46212547, 1.57862899, 1.1139206 ],
       [1.36841365, 1.36074842, 1.88001849, 1.27454204],
       [1.22458118, 1.81397318, 1.05820075, 1.73015342]])

## differences between rand,randn,randint, and uniform :


Function|	Distribution	|Range	|Output Type
--------|---------------|-------|-----------
**`rand`**|	Uniform|	[0, 1)	|Floating-point
**`randn`**|	Standard Normal(mean=0, std=1)	|Approximately [-3, 3]	|Floating-point
**`randint`**|	Uniform (Discrete)	[low, high) |(integer range)	|Integer
**`uniform`**|	Uniform|	[low, high)|	Floating-point