<a href="https://colab.research.google.com/github/DhanaTejaDumpa/numpy_practise/blob/main/004_29Jan25_stacking_and_split_task5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### 1) Given two 1D arrays, a = [1, 2, 3] and b = [4, 5, 6], use NumPy to vertically stack them. What is the result?

In [1]:
import numpy as np

In [10]:
a = [1,2,3]
b = [4,5,6]
a,b                   # a and b are two 1D arrays

([1, 2, 3], [4, 5, 6])

In [11]:
np.vstack((a,b))

array([[1, 2, 3],
       [4, 5, 6]])

**Note :** In case of 1D arrays, vstack returns a 2D output.

### 2)How can you stack two 2D arrays A and B vertically, where A has the shape (2, 3) and B has the shape (2, 3)?

In [19]:
A = np.arange(6).reshape(2,3)
B = np.arange(6,12).reshape(2,3)

A,B      # A and B are two 2D arrays

(array([[0, 1, 2],
        [3, 4, 5]]),
 array([[ 6,  7,  8],
        [ 9, 10, 11]]))

In [20]:
np.vstack((A,B))

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

**Note :** since both arrays have same number of columns,so they can be vertically stacked.

### 3.What is the result of horizontally stacking two arrays x = [1, 2, 3] and y = [4, 5, 6] in NumPy?

In [22]:
x = [1,2,3]
y = [4,5,6]

x,y    # x and y are 1D arrays

([1, 2, 3], [4, 5, 6])

In [21]:
np.hstack((x,y))

array([1, 2, 3, 4, 5, 6])

**Note :** In case of 1D ,hstack returns same dimensional output i.e., 1D

### 4) How would you combine two 2D arrays A of shape (3, 2) and B of shape (3, 2) horizontally using NumPy?

In [23]:
A = np.arange(6).reshape(3,2)
B = np.arange(6,12).reshape(3,2)

A,B

(array([[0, 1],
        [2, 3],
        [4, 5]]),
 array([[ 6,  7],
        [ 8,  9],
        [10, 11]]))

In [24]:
np.hstack((A,B))

array([[ 0,  1,  6,  7],
       [ 2,  3,  8,  9],
       [ 4,  5, 10, 11]])

**Note :** since both arrays have same number of rows,so they can be horizontally stacked.

### 5) Given a 1D array arr = [10, 20, 30, 40, 50, 60], use NumPy to split the array into three equal parts.

In [8]:
arr = np.array([10, 20, 30, 40, 50, 60])
np.split(arr,3)        # syntax : np.split(array,sections)  ,by default axis = 0

[array([10, 20]), array([30, 40]), array([50, 60])]

### 6.Given the 1D NumPy array arr = [10, 20, 30, 40, 50, 60, 70, 80, 90, 100], use NumPy to split the array into four parts where:
* The first part has 3 elements,
* The second part has 2 elements,
* The third part has 4 elements,
* The fourth part contains the remaining elements.


In [9]:
arr = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])
np.array_split(arr,[3,5,9])   # syntax : np.array_split(array,indices) by default axis = 0

[array([10, 20, 30]), array([40, 50]), array([60, 70, 80, 90]), array([100])]