<a href="https://colab.research.google.com/github/DhanaTejaDumpa/numpy_practise/blob/main/Numpy_assignment_day_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### NumPy Exercises
##### Now that we've learned about NumPy let's test your knowledge. We'll start off with a few simple tasks and then you'll be asked some more complicated questions.
##### IMPORTANT NOTE! Make sure you don't run the cells directly above the example output shown, otherwise you will end up writing over the example output!

##### import numpy as np


###### 1. Write a NumPy program to find the missing data in a given array.

In [ ]:
### code here

import numpy as np

Original_array = np.array([[3, 2,np.nan, 1],[10, 12, 10, 9],[5,np.nan, 1, np.nan]])

print(f'Original array : \n {Original_array}')

print(f'\nFind the missing data of the said array : \n {np.isnan(Original_array)}')

# np.isnan() function checks each element of array and returns new arrayof the same shape.where,it returns True for missing values and False for valid values

Original array : 
 [[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array : 
 [[False False  True False]
 [False False False False]
 [False  True False  True]]


In [ ]:
## sample output

Original array:
[[ 3.  2. nan  1.]
 [10. 12. 10.  9.]
 [ 5. nan  1. nan]]

Find the missing data of the said array:
[[False False  True False]
 [False False False False]
 [False  True False  True]]


##### 2. Write a NumPy program to check whether two arrays are equal (element wise) or not.

In [ ]:
### code here

arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(1,10).reshape(3,3)

print(f'Elemnt-wise comparision :\n',arr1 == arr2)
print(f'Two arrays are equal : ',np.array_equal(arr1,arr2))

Elemnt-wise comparision :
 [[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
Two arrays are equal :  True


In [ ]:
arr1 = np.arange(1,10).reshape(3,3)
arr2 = np.arange(5,14).reshape(3,3)

print(f'Elemnt-wise comparision :\n',arr1 == arr2)
print(f'Two arrays are equal : ',(arr1 == arr2).all())

Elemnt-wise comparision :
 [[False False False]
 [False False False]
 [False False False]]
Two arrays are equal :  False


###### 3. Write a NumPy program to create a 4x4 array with random values, now create a new array from the said array swapping first and last rows.

In [ ]:
## code here
arr = np.arange(16).reshape(4,4)
print(f'Orginal array: \n',arr)
print(f'\n New array after swapping first and last rows of the said array:\n',arr[::-1])

Orginal array: 
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

 New array after swapping first and last rows of the said array:
 [[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [ ]:
## sample output

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

New array after swapping first and last rows of the said array:
[[12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


###### 4. Write a NumPy program to convert a list and tuple into arrays.

In [ ]:
#### code here

my_list = [1,2,3,4,5,6,7,8]
print(f'List to array : \n',np.asarray(my_list))

my_tuple = (8,4,6,1,2,3)
print(f'\nTuple to array : \n',np.asarray(my_tuple))

List to array : 
 [1 2 3 4 5 6 7 8]

Tuple to array : 
 [8 4 6 1 2 3]


###### 5. Write a NumPy program to find common values between two arrays.

In [ ]:
### code here
arr1 = np.array([10,20,30,40,50])
arr2 = np.array([20,40])
print(f'Common values between two arrays : ',np.intersect1d(arr1,arr2))

# np.intersect1d() works with only 1D.

Common values between two arrays :  [20 40]


In [ ]:
# for 2D arrays

import numpy as np

arr1 = np.array([[10,20,30],[40,50,60]])
arr2 = np.array([[30,40,50],[60,70,80]])
common_values = np.intersect1d(arr1.flatten(),arr2.flatten())
common_values = common_values.reshape(2,2)
print(f'Common values between two arrays : \n',common_values)

Common values between two arrays : 
 [[30 40]
 [50 60]]


###### 6. Write a NumPy program to create a new shape to an array without changing its data.

In [ ]:
### code here

arr = np.arange(1,7).reshape(3,2)
print(f'Original array :\n ', arr)
print(f'Reshaped array :\n ',arr.reshape(2,3))

Original array :
  [[1 2]
 [3 4]
 [5 6]]
Reshaped array :
  [[1 2 3]
 [4 5 6]]


In [ ]:
### sample output


###### 7. Write a NumPy program to count the frequency of unique values in numpy array.

In [ ]:
### code here
arr = np.array([10,10,20,10,20,20,20,30,30,50,40,40])
print(f'Original array :\n',arr)
unique_values,counts = np.unique(arr,return_counts = True)
print(f'Frequency of unique values of the said array :\n ',np.vstack((np.array(unique_values),np.array(counts))))

Original array :
 [10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array :
  [[10 20 30 40 50]
 [ 3  4  2  2  1]]


In [ ]:
## sample output

Original array:
[10 10 20 10 20 20 20 30 30 50 40 40]
Frequency of unique values of the said array:
[[10 20 30 40 50]
 [ 3  4  2  2  1]]


###### 8. Write a NumPy program to broadcast on different shapes of arrays where p(3,3) + q(3).

In [ ]:
### code here
arr1 = np.array([[0,0,0],[1,2,3],[4,5,6]])
arr2 = np.array([10,11,12])
print(f'Original arrays :')
print(f'Array-1 :\n',arr1)
print(f'Array-2 :\n',arr2)
print(f'\nNew Array :\n',arr1+arr2)

Original arrays :
Array-1 :
 [[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2 :
 [10 11 12]

New Array :
 [[10 11 12]
 [11 13 15]
 [14 16 18]]


In [ ]:
## sample output

Original arrays:
Array-1
[[0 0 0]
 [1 2 3]
 [4 5 6]]
Array-2
[10 11 12]

New Array:
[[10 11 12]
 [11 13 15]
 [14 16 18]]


###### 9. Write a NumPy program to extract all the elements of the second row from a given (4x4) array.

In [ ]:
### code here

arr = np.arange(0,16).reshape(4,4)
print(f'Original array :\n',arr)
print(f'\nExtracted data : Second row\n',arr[1,:])

Original array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data : Second row
 [4 5 6 7]


In [ ]:
import numpy as np
arra_data = np.arange(0,16).reshape((4, 4))
print("Original array:")
print(arra_data)
print("\nExtracted data: Second row")
print(arra_data[1,:])

Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Second row
[4 5 6 7]


###### 10. Write a NumPy program to extract third and fourth elements of the first and second rows from a given (4x4) array.

In [ ]:
## code here

import numpy as np
arr = np.arange(0,16).reshape(4,4)
new_arr = arr[0:2,2:4]
print(f'Original array :\n',arr)
print(f'\nExtracted data :\n',new_arr)

Original array :
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data :
 [[2 3]
 [6 7]]


In [ ]:
## sample output


Original array:
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]

Extracted data: Third and fourth elements of the first and second rows 
[[2 3]
 [6 7]]


###### 11. Write a NumPy program to get the dates of yesterday, today and tomorrow.

In [ ]:
### code here

import numpy as np
today = np.datetime64('today','D')
yesterday = today - np.timedelta64(1,'D')
tomorrow = today + np.timedelta64(1,'D')
print(f'Yesterday : ',yesterday)
print(f'Today : ',today)
print(f'Tomorrow : ',tomorrow)

Yesterday :  2025-02-15
Today :  2025-02-16
Tomorrow :  2025-02-17


###### 12. Write a NumPy program to find the first Monday in May 2017.

In [ ]:
## code here
import numpy as np


first_monday = np.busday_offset('2017-05-01', 0, roll='forward', weekmask='Mon')

print("First Monday in May 2017 is:\n", first_monday)



First Monday in May 2017 is:
 2017-05-01


      syntax : np.busday_offset(start_date, offset, roll='forward', weekmask='Mon')


* start_date → The reference date (e.g., '2017-05-01').
* offset → The number of business days to shift.
* roll → Determines whether to adjust the date if it’s not a business day.
* weekmask → Specifies which days are considered valid (e.g., 'Mon' for Mondays only).

In [ ]:
## sample output

First Monday in May 2017:
2017-05-01
